export const protectedRoutes = [
  "/",
  "/about-us",
  "/contact-us",
  "/post",
  "/post/:page",
  "/user",
  "/user/:page*",
  "/admin",
  "/admin:page*",
  "/login",
  "/registration",
  "/terms-and-condition",
  "/privacy-policy",
  "/all-users",
];
